### ISSUE TITLE
paper.md suggestions

### ISSUE THREAD

**Issue by Zitzeronion** [obertscheiderfhwn/RTMsim#2]
Dear @obertscheiderfhwn 

First I want to point the huge improvements this package has seen in the last few days, congrats to that 👍.
Concerning the review for [JOSS](https://github.com/openjournals/joss-reviews/issues/4763) I have some minor issues with the paper.
See the attached file, my main criticism concerns missing references and some other small things.
Let me know what you think about it.

[paper.md](https://github.com/obertscheiderfhwn/RTMsim/files/10778251/paper.md)

**Comment by Zitzeronion** [comment]
I think it's helpful to have some length scales depict at Figure 1.
![rtm_pic1_suggestion](https://user-images.githubusercontent.com/26249811/219981884-5e4452e6-0cb9-4a11-b0aa-685f26c7e71c.png)

**Comment by obertscheiderfhwn** [comment]
Dear @Zitzeronion, I updated the the paper according to (hopefully all) your suggestions. Please have a look at the new version:
[paper_20230221.pdf](https://github.com/obertscheiderfhwn/RTMsim/files/10797759/paper_20230221.pdf)

**Comment by Zitzeronion** [comment]
Thanks for the additions to the paper, especially the modeling equations.
There is one more improve for the overall readability of the paper, namely the reduction of size of Fig. 4-5.
Apart from that green light for the paper from my side.

**Comment by obertscheiderfhwn** [comment]
Green light refers to the small green circles in Fig. 4 and 5?

**Comment by Zitzeronion** [comment]
Figure 4-5 fill a whole page each, I think the paper would not suffer if you downscale these plots a little and put the table (which is now part of Fig 4 -> Fig 4b) in the text as a markdown table.

No, the green light refers to the state of the paper and that I am overall satisfied (given this minor stylistic thing are changed) 👍

**Comment by obertscheiderfhwn** [comment]
OK, will change today.

**Comment by obertscheiderfhwn** [comment]
Changes implemented and pdf created on https://github.com/openjournals/joss-reviews/issues/4763

**Comment by Zitzeronion** [comment]
Thanks for the additional work on the paper 👍
