### ISSUE TITLE
Docstrings for functions

### ISSUE THREAD

**Issue by Zitzeronion** [obertscheiderfhwn/RTMsim#4]
Sorry @obertscheiderfhwn for taking my time on the package 😅 
There are some things that I would like you implement in order to check of the remain boxes of the [Joss submission](https://github.com/openjournals/joss-reviews/issues/4763)

The functions:
- `create_coordinate_system( )`
- `assign_parameters( )`
- `create_faces( )`
- `gui( )`
don't have proper docstrings, please add at least an argument section to the docstrings. 
They don't need to be as precise as outlined in the [official Julia docs](https://docs.julialang.org/en/v1/manual/documentation/), but some more documentation would be helpful.

**Comment by obertscheiderfhwn** [comment]
Recommendations added 👍

**Comment by obertscheiderfhwn** [comment]
Docstrings added for the four functions:
https://obertscheiderfhwn.github.io/RTMsim/build/functions/#rtmsim.create_coordinate_systems-Tuple{Any}
https://obertscheiderfhwn.github.io/RTMsim/build/functions/#rtmsim.assign_parameters-Tuple{Any}
https://obertscheiderfhwn.github.io/RTMsim/build/functions/#rtmsim.create_faces-Tuple{Any}
https://obertscheiderfhwn.github.io/RTMsim/build/functions/#rtmsim.gui-Tuple{}

**Comment by Zitzeronion** [comment]
Thank you for the additional work on the documentation of the functions. This closes the docstring issue I raised for [Joss](https://github.com/openjournals/joss-reviews/issues/4763)
