### ISSUE TITLE
Unit test for `numerical_flux_function`

### ISSUE THREAD

**Issue by Zitzeronion** [obertscheiderfhwn/RTMsim#5]
Similar to [issue](https://github.com/obertscheiderfhwn/RTMsim/issues/4) one the remaining boxes for the [Joss paper](https://github.com/openjournals/joss-reviews/issues/4763) covers testing.

I do like the integration test that comes with the package.
For any further development unit tests could help to reduce the time spend debugging.
There are two functions that would benefit from an unit test:
-`numerical_flux_function( )`
-`numerical_flux_function_boundary( )`

If you find yourself having trouble implementing an unit test let me know and I can write a PR.

**Comment by obertscheiderfhwn** [comment]
Recommendations added 👍

**Comment by obertscheiderfhwn** [comment]
Unit tests added for the two functions:
https://obertscheiderfhwn.github.io/RTMsim/build/functions/#rtmsim.numerical_flux_function-Tuple{Any}
https://obertscheiderfhwn.github.io/RTMsim/build/functions/#rtmsim.numerical_flux_function_boundary-Tuple{Any}

Hope this is what you meant.

**Comment by Zitzeronion** [comment]
That is a good starting point.
Having tests in the docstrings is of course helpful, but I was looking for tests in the runtest file.
Imagine I want to work on `numerical_flux_function` and have some ideas.
I implement changes and call `julia> ] test` to see if I have broken something.
Right now I could break something and the test would work, because in your runtest file contains no `@test` statement.

Could you take the docstring tests and put them into the runtest file?
This is generally a good idea, because within your CI (continuous integration) file (the `.yaml` file in the github folder) you can automate testing and be aware about breaking changes.
And as a user and contributor I can simply call `julia> ] test` to check if my code works or breaks something.

**Comment by obertscheiderfhwn** [comment]
The runtests.jl now includes unit tests for the numerical flux functions, running a typical simulation and creating a contour plot from the simulation results. 

Automated testing with GitHub actions was not so easy to implement since rtmsim is using the package GLMakie with windows on a headless environment. But I copied relevant section from GLMakie's ci.yml file to run the tests.

Successfully passed a test:
https://github.com/obertscheiderfhwn/RTMsim/actions/runs/4355606962/jobs/7612454744

**Comment by Zitzeronion** [comment]
Well done, but that was not my intention and there is still no test.
Sorry for being not clear in my description, but try to have a look at [DataFrames.jl](https://github.com/JuliaData/DataFrames.jl) [test suit](https://github.com/JuliaData/DataFrames.jl/blob/main/test/index.jl) for a clearer understanding. 

Basically the idea is that you execute a mathematical function, say y(x) = x^2, so you know that for x = 3 the function should return 9. In `runtests.jl` you can do the same, by knowing the input you know the output.
In file square.jl
```julia
function y(x)
  return x^2 
end
```
and in `runtest.jl` of this package you can do
```julia
@test y(3) == 9
```
Now, if `y(x)` gets modified due to contributions this test would at least ensure that for the input of x=3 has to return 9 (the square of 3). I am asking to use `numerical_flux_function` with an well defined input and write in `runtests.jl`
```julia
@test numerical_flux_function(inputs ...) == output
```
no integration into a full simulation just the singular function.

**Comment by obertscheiderfhwn** [comment]
Got it. And have already an idea what and how to implement.

**Comment by obertscheiderfhwn** [comment]
I implemented unit tests for the numerical flux functions. The unit tests check if the calculated flux is consistent.

For example: Numerical flux function is equal to analytical flux function if values in both cells are equal and cell face is normal to either u- or v-direction. For example, if cell face is normal to u- direction: F([rho_val,u_val,v_val,gamma_val],[rho_val,u_val,v_val,gamma_val])=[rho_val*u_val,rho_val*u_val*u_val,gamma_val*u_val and u_val]. The convective contribution in the flow fraction equation for gamma is rewritten: u \cdot (\nabla gamma) is rewritten as \div(gamma u)-gamma*\div(u). That's the reason for two parts for the numerical flux for gamma.

This is the code snippet:
```
rho_val=1.0
u_val=1.2
v_val=0.4
gamma_val=0.9
n1_val=1.0
n2_val=0.0
A_val=1.0
input_struct=rtmsim.input_args_flux(1,[rho_val; u_val; v_val; gamma_val],[rho_val; u_val; v_val; gamma_val],[n1_val; n2_val; A_val]);return_struct=rtmsim.numerical_flux_function(input_struct);
#println("F_rho="*string(return_struct.F_rho_num_add)*", F_u="*string(return_struct.F_u_num_add)*", F_v="*string(return_struct.F_v_num_add)*", F_gamma="*string(return_struct.F_gamma_num_add)*", F_gamma1="*string(return_struct.F_gamma_num1_add))
@test return_struct.F_rho_num_add==rho_val*u_val && return_struct.F_u_num_add==rho_val*u_val*u_val && return_struct.F_gamma_num_add==gamma_val*u_val && return_struct.F_gamma_num1_add==u_val
```

**Comment by obertscheiderfhwn** [comment]
In addition to the consistency checks, I added new tests where the one-dimensional Burgers u_t+(0.5*u*u)_x=0 equation is solved with the different methods from rtmsim.numerical_flux_function. The integrated area under the u-distribution is integrated and compared with the analytical solution.

Hope the tests are now sufficient.

**Comment by Zitzeronion** [comment]
Thanks for the additions.
I created a [PR](https://github.com/obertscheiderfhwn/RTMsim/pull/7) with some minor suggestions concerning this.
Let me know what you think.

**Comment by obertscheiderfhwn** [comment]
Thanks for suggestions and contribution. Just merged your commit.
